https://cafe.naver.com/esaa2019?iframe_url_utf8=%2FArticleRead.nhn%253Fclubid%3D29858915%2526page%3D1%2526menuid%3D80%2526boardtype%3DL%2526articleid%3D2297%2526referrerAllArticles%3Dfalse

기한: 9월 11일 (월) 18시 30분

과제: 1) 파이썬 머신러닝 완벽가이드 pg. 39~86를 필사하여 깃허브에 업로드한 뒤, 깃허브 링크를 댓글로 달아주세요.

2) 아래 넘파이 문제를 끝까지 풀고(26~39번) 깃허브에 업로드한 뒤, 깃허브 링크를 댓글로 달아주세요.

# 1. 파이썬 머신러닝 완벽가이드 pg. 39~86

In [10]:
competition_name = "titanic"

# Mount your Google Drive.
from google.colab import drive
drive.mount("/content/drive")

kaggle_creds_path = "PATH_TO_YOUR_TOKEN"

!pip install kaggle --quiet

#!mkdir ~/.kaggle
#!cp PATH_TO_YOUR_TOKEN ~/.kaggle/
#!chmod 600 ~/.kaggle/kaggle.json

!kaggle competitions download -c {competition_name}

!mkdir kaggle_data
!unzip {competition_name + ".zip"} -d kaggle_data

# Unmount your Google Drive
drive.flush_and_unmount()

Mounted at /content/drive
titanic.zip: Skipping, found more recently modified local copy (use --force to force download)
mkdir: cannot create directory ‘kaggle_data’: File exists
Archive:  titanic.zip
replace kaggle_data/gender_submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: kaggle_data/gender_submission.csv
replace kaggle_data/test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: kaggle_data/test.csv
replace kaggle_data/train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: kaggle_data/train.csv

## 04 데이터 핸들링 - 판다스
2차원 데이터를 효율적으로 가공/처리할 수 있는 라이브러리

### 판다스 시작 - 파일을 dataframe으로 로딩, 기본 API
메타 데이터 조회
* `info()` - 총 데이터 건수, 데이터 타입, Null 건수
* `describe()` - column별 숫자형 데이터값의 n-percentile 분포도, 평균값, 최댓값, 최솟값
* `value_counts()` - 해당 column값의 유형과 건수 확인, 데이터 분포도 확인에 유용

In [8]:
import pandas as pd

In [15]:
#from google.colab import drive
#drive.mount('/content/drive')
titanic_df = pd.read_csv('/content/drive/MyDrive/4-2/ESAA/data/titanic/train.csv')
drive.flush_and_unmount()
print(type(titanic_df))
titanic_df.head(3)

<class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [16]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [17]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [18]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64

In [20]:
# []에 칼럼 이름을 넣으면 해당 칼럼에 해당하는 series 객체를 반환
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

In [21]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

### Dataframe, list, dictionary, numpy dnarray 상호변환

In [22]:
import numpy as np

In [23]:
col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print(array1.shape)

(3,)

In [24]:
# 리스트를 이용해 Dataframe 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print(df_list1)

   col1
0     1
1     2
2     3

In [25]:
# numpy ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)
print(df_array1)

   col1
0     1
1     2
2     3

In [26]:
col_name2 = ['col1', 'col2', 'col3']
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)
print(array2.shape)

(2, 3)

In [27]:
# 2차원 리스트를 이용해 Dataframe 생성
df_list2 = pd.DataFrame(list2, columns=col_name2)
print(df_list2)

   col1  col2  col3
0     1     2     3
1    11    12    13

In [28]:
# 2차원 numpy ndarray를 이용해 DataFrame 생성
df_array2 = pd.DataFrame(array2, columns=col_name2)
print(df_array2)

   col1  col2  col3
0     1     2     3
1    11    12    13

In [31]:
# 딕셔너리로 만든 DataFrame
dict = {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33

In [32]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print(type(array3), array3.shape)
print(array3)

<class 'numpy.ndarray'> (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [33]:
# DataFrame -> list
list3 = df_dict.values.tolist()
print(list3)

# DataFrame -> dictionary
dict3 = df_dict.to_dict('list')
print(dict3)

[[1, 2, 3], [11, 22, 33]]
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

### Dataframe의 칼럼 데이터 세트 생성과 수정

In [49]:
titanic_df['Age_0'] = 0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [50]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [51]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

### DataFrame 데이터 삭제: drop( )

In [52]:
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1

In [55]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
# inplace = True 로 drop 한 후 반환된 값: None
print(drop_result)
titanic_df.head(3)

KeyError: ignored

In [57]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)

print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

KeyError: ignored

### Index 객체
DataFrame, Series 의 레코드를 고유하게 식별하는 객체\
1차원 array이기 때문에 ndarray처럼 단일 값 반환 및 슬라이싱 가능\
하지만 객체의 값을 임의로/함부로 변경할 수 는 없음

In [58]:
# 원본 파일 다시 로딩
from google.colab import drive
drive.mount('/content/drive')
titanic_df = pd.read_csv('/content/drive/MyDrive/4-2/ESAA/data/titanic/train.csv')
drive.flush_and_unmount()

Mounted at /content/drive

In [59]:
# Index 객체 추출
indexes = titanic_df.index
print(indexes)

RangeIndex(start=0, stop=891, step=1)

In [62]:
print(indexes.values)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [64]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[6])
print(indexes.values[6])
print(indexes.values[:5])
print(indexes[:5].values)

<class 'numpy.ndarray'>
(891,)
6
6
[0 1 2 3 4]
[0 1 2 3 4]

DataFrame 및 Series에 `reset_index()`를 수행하면 새롭게 index를 연속 숫자 형으로 할당하며 원래의 index는 새로운 칼럼 'index'로 추가된다.

In [65]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

Series에 reset_index()를 하면 index 칼럼이 추가되기 때문에 Series가 아닌 DataFrame이 반환됨

In [66]:
print('#### A Series before reset_index ####')
a = titanic_df['Pclass'].value_counts()
print(a)
print(type(a))


print('#### A Series after reset_index ####')
b = a.reset_index(inplace=False)
print(b)
print(type(b))

#### A Series before reset_index ####
3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>
#### A Series after reset_index ####
   index  Pclass
0      3     491
1      1     216
2      2     184
<class 'pandas.core.frame.DataFrame'>

### Data selection, filtering
`[]`, `ix[]`, `iloc[]`, `loc[]`, boolean indexing\
* DataFrame 뒤의 '`[]`'는 칼럼만 지정할 수 있는 연산자로 이해하는 것이 좋음
* `ix[]` 는 사라짐
* `iloc[]` 는 위치 기반 인덱싱만 허용
* `loc[]` 는 명칭 기반 데이터 추출

In [67]:
titanic_df['Pclass'].head(3)

0    3
1    1
2    3
Name: Pclass, dtype: int64

In [69]:
titanic_df[['Survived','Pclass']].head(3)

   Survived  Pclass
0         0       3
1         1       1
2         1       3

In [70]:
titanic_df[0:2]

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [73]:
# Data selection
titanic_df[titanic_df['Pclass']==3].head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

In [84]:
titanic_df.iloc[0,3]

'Braund, Mr. Owen Harris'

In [83]:
titanic_df.loc[0, 'Name']

'Braund, Mr. Owen Harris'

In [87]:
titanic_boolean = titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean.head(3)

<class 'pandas.core.frame.DataFrame'>

    PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked
33           34         0       2  Wheadon, Mr...  male  66.0      0      0  C.A. 24579  10.5000   NaN        S
54           55         0       1  Ostby, Mr. ...  male  65.0      0      1      113509  61.9792   B30        C
96           97         0       1  Goldschmidt...  male  71.0      0      0    PC 17754  34.6542    A5        C

### 정렬, Aggregation 함수, GroupBy 적용


*   `sort_values()` - Dataframe, series의 정렬
*   Aggregation 함수 적용
* `groupby()` 적용

### 결손 데이터 처리하기
* isna() - 결손 데이터 여부 확인
* fillna() - 결손 데이터 대체

### apply lambda 식으로 데이터 가공